### <a name='0'></a> Import of libraries

In [91]:
import numpy as np
np.set_printoptions(suppress=True, precision=4)
np.random.seed(42)
#np.__version__

### <a name='1'></a> Exercise 1
Check if all array elements $ A, B, C $ and $ D $ return the logical value _True_.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])
```

In [5]:
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])

D = np.array([0.1, 0.3])

for array in zip(list((A,B,C,D))):
    print(np.all(array))

True
False
False
True


### <a name='2'></a> Exercise 2
Check if all array elements $ A, B $ and $ C $ return the logical value _True_ along the axis with index 1.

```
A = np.array([[3, 2, 1, 4],
              [5, 2, 1, 6]])

B = np.array([[3, 2, 1, 4],
              [5, 2, 0, 6]])

C = np.array([[True, False, False],
              [True, True, True]])
```

In [7]:
for array in zip(list((A,B,C))):
    print(np.all(array,axis=1))

[[ True  True  True  True]]
[[ True  True False  True]]
[[ True False False]]


### <a name='3'></a> Exercise 3
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [8]:
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])

for array in zip(list((A,B,C,D))):
    print(np.any(array))

False
True
True
True


### <a name='4'></a> Exercise 4
Check if any element of arrays $ A, B, C $ and $ D $ returns the logical value _True_ along the axis with index 0.

```
A = np.array([[0, 0, 0],
              [0, 0, 0]])

B = np.array([[0, 0, 0],
              [0, 1, 0]])

C = np.array([[False, False, False],
              [True, False, False]])

D = np.array([[0.1, 0.0]])
```

In [9]:
for array in zip(list((A,B,C,D))):
    print(np.any(array,axis=0))

[[False False False]
 [False False False]]
[[False False False]
 [False  True False]]
[[False False False]
 [ True False False]]
[[ True False]]


### <a name='5'></a> Exercise 5
Check the array $ A $ for missing data (_np.nan_).

```
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
```

In [10]:
A = np.array([[3, 2, 1, np.nan],
              [5, np.nan, 1, 6]])
np.isnan(A)

array([[False, False, False,  True],
       [False,  True, False, False]])

### <a name='6'></a> Exercise 6
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise) with the specified tolerance level.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
```

In [13]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])

np.allclose(A,B)

True

### <a name='7'></a> Exercise 7
Check if the following arrays $ A $ and $ B $ are equal in terms of elements (element-wise). Use the comparison operator _==_.

```
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.3999999999, 0.5000000001, 0.3])
```

In [15]:
A = np.array([0.4, 0.5, 0.3])
B = np.array([0.39999999, 0.5000001, 0.3])
print(A==B)

[False False  True]


### <a name='8'></a> Exercise 8

Check which elements (element-wise) from the array $ A $ below have higher values than the array $ B $.

```
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
```

In [16]:
A = np.array([0.4, 0.5, 0.3, 0.9])
B = np.array([0.38, 0.51, 0.3, 0.91])
print(A>B)

[ True False False False]


### <a name='9'></a> Exercise 9

Create an array of numpy dimensions _4x4_ filled with zeros. Set the data type to _int_.

__Expected result:__

```
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])
```

In [19]:
np.full((4,4),0)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### <a name='10'></a> Exercise 10
Create an array of numpy dimensions _10x10_ filled with number 255. Set the data type to _float_.

__Expected result:__
```
array([[255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.],
       [255., 255., 255., 255., 255., 255., 255., 255., 255., 255.]])
```

In [20]:
np.full((10,10),255)

array([[255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255],
       [255, 255, 255, 255, 255, 255, 255, 255, 255, 255]])

### <a name='1'></a> Exercise 11
Build a one-dimensional numpy array of two-digit numbers.

__Expected result:__
```
array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])
```

In [26]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

### <a name='2'></a> Exercise 12

Build the numpy array specified below:

```
array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])
```

In [25]:
np.arange(10,100).reshape(-1,10)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

## <a name='3'></a> Exercise 13

Build a _6x6_ two-dimensional array - identity matrix. Use the _int_ data type.

__Expected result:__

```
array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1]])
```

In [30]:
np.identity(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

### <a name='4'></a> Exercise 14

Set the random seed to 10. Then build a one-dimensional array consisting of 30 pseudo-randomly generated values from the uniform distribution above the $ [0, 1) $ interval.

__Expected result:__

```
array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])
```

In [35]:
np.random.seed(10)
np.random.rand(30)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578,
       0.54254437, 0.14217005, 0.37334076, 0.67413362, 0.44183317,
       0.43401399, 0.61776698, 0.51313824, 0.65039718, 0.60103895])

### <a name='5'></a> Exercise 15

Set the random seed to 20. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the standard normal distribution $ N (0, 1) $.

__Expected result:__
```
array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])
```

In [37]:
np.random.seed(20)
np.random.randn(10,4)

array([[ 0.88389311,  0.19586502,  0.35753652, -2.34326191],
       [-1.08483259,  0.55969629,  0.93946935, -0.97848104],
       [ 0.50309684,  0.40641447,  0.32346101, -0.49341088],
       [-0.79201679, -0.84236793, -1.27950266,  0.24571517],
       [-0.0441948 ,  1.56763255,  1.05110868,  0.40636843],
       [-0.1686461 , -3.18970279,  1.12013226,  1.33277821],
       [-0.24333877, -0.13003071, -0.10901737,  1.55618644],
       [ 0.12877835, -2.06694872, -0.88549315, -1.10457948],
       [ 0.93286635,  2.059838  , -0.93493796, -1.61299022],
       [ 0.52706972, -1.55110074,  0.32961334, -1.13652654]])

### <a name='6'></a> Exercise 16
Set the random seed to 30. Then build a two-dimensional array with the shape _(10, 4)_ pseudo-random values generated from the normal distribution $ N (100, 5) $.
$\mu=100$   
$\sigma^{2}=5$

__Expected result:__
```
array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])
```

In [39]:
np.random.seed(30)
sigma = np.sqrt(5)
mu = 100

sigma * np.random.randn(10, 4) + mu

array([[ 97.17349231, 103.41650023,  97.82942436, 101.05220329],
       [ 99.7748353 , 100.67930221,  96.14063068, 103.544381  ],
       [100.30029631,  97.52499594, 103.52901961, 100.24037271],
       [ 98.29153712,  98.2666258 , 103.09437633, 101.70027274],
       [ 99.36127721, 101.20382627,  95.34026547, 102.09694365],
       [ 99.98708001,  98.95468525,  99.05410904, 102.38025432],
       [ 93.50787269, 103.61547679, 103.18753701,  98.51356237],
       [102.20256689,  96.19764407,  97.54000366,  97.05813038],
       [101.81233513,  97.66380453,  98.45883627,  98.09317768],
       [102.48979932,  95.70413391,  98.43161651, 101.89861815]])

### <a name='7'></a> Exercise 17
Iterating by array numpy $ A $ element by element (element-wise) print each element of the array to the console.

```
A = np.array([[1, 4, 3],
              [5, 2, 6]])
```

In [44]:
A = np.array([[1, 4, 3],
              [5, 2, 6]])
for i in np.nditer(A) :
    print(i)

1
4
3
5
2
6


### <a name='8'></a> Exercise 18
Create a one-dimensional numpy array (vector) consisting of 11 equally spaced points from the interval $ [0, 1]. $

__Expected result:__
```
array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])
```

In [46]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### <a name='9'></a> Exercise 19

Set the random seed to 42. Generate a one-dimensional array (vector) containing the possible result from the Big Lotto game.

__Expected result:__
```
array([39, 29, 15, 43,  8, 21])
```

In [47]:
np.random.seed(42)
np.random.randint(low=1, high=50, size=6)

array([39, 29, 15, 43,  8, 21])

### <a name='10'></a> Exercise 20

> Indented block


Build the two-dimensional _6x6_ size array below:

```
array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])
```

In [48]:
np.diag(np.arange(6))

array([[0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0],
       [0, 0, 0, 3, 0, 0],
       [0, 0, 0, 0, 4, 0],
       [0, 0, 0, 0, 0, 5]])

### <a name='3'></a> Exercise 21
Generate and convert the following numpy array into a list:

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

In [52]:
a=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
a.tolist()

[[0, 1, 2, 3], [4, 5, 6, 7], [8, 9, 10, 11]]

### <a name='4'></a> Exercise 22
The following numpy array is given:
```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
```

Using the cut operator, transform the array into the following:

* swap rows (first with last)

```
array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])
```

In [4]:
array=np.array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
array[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [5]:
array[:,::-1]

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

In [6]:
array [::-1,::-1]

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

### <a name='5'></a> Exercise 23
The following numpy array:

```
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
```
Transform to array:

```
array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])
```

In [10]:
array=np.array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])
np.pad(array,1,constant_values= 0)

array([[0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0.]])

### <a name='6'></a> Exercise 24
The following numpy array:
```
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
```

Transform to array:
```
array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])
```

In [11]:
array=np.array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])
array[::2, ::2] = 10
array[1::2, ::2] = 5
array

array([[10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0],
       [10,  0, 10,  0, 10,  0],
       [ 5,  0,  5,  0,  5,  0]])

### <a name='7'></a> Exercise 25
Combine the following arrays: $ A $ and $ B $ into one array.

```
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
```

__The expected result:__

```
array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])
```

In [16]:
A = np.arange(12).reshape(-1, 4)
B = np.array([[4, 3, 7, 2],
              [0, 5, 2, 6]])
C=np.append(A,B,axis=0)
C

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 4,  3,  7,  2],
       [ 0,  5,  2,  6]])

### <a name='8'></a> Exercise 26
Use the $ A $ and $ B $ arrays below to extract the common elements (intersection) of the arrays.

```
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])      
```

In [18]:
A = np.arange(8).reshape(-1, 4)
B = np.array([[9, 10, 11, 3],
              [2, 8, 0, 9]])
np.intersect1d(A,B)

array([0, 2, 3])

### <a name='9'></a> Exercise 27
The following numpy array $ A $ is given.
Find the unique values of this array.

```
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
```

In [20]:
A = np.array([[5, 1, 2, 1, 2],
              [9, 1, 9, 7, 5],
              [4, 1, 5, 7, 9]])
np.unique(A)

array([1, 2, 4, 5, 7, 9])

### <a name='10'></a> Exercise 28
The array below is given:
```
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
```
Return indexes with maximum values for a given row.

In [23]:
A = np.array([[0.4, 0.3, 0.3],
              [0.1, 0.1, 0.8],
              [0.2, 0.5, 0.3]])
np.max(A,0)

array([0.4, 0.5, 0.8])

### <a name='1'></a> Exercise 29
Sort the array $ A $ below:
* by row (ascending)
* by column (ascending)

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [24]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])

In [27]:
np.sort(A)

array([[ 3.49,  4.99,  9.99],
       [ 1.99,  4.99,  9.99],
       [ 2.39,  7.29, 14.99]])

In [28]:
np.sort(A,0)

array([[ 1.99,  2.39,  4.99],
       [ 4.99,  3.49,  7.29],
       [14.99,  9.99,  9.99]])

### <a name='2'></a> Exercise 30
Extract all elements of the $ A $ array with a value greater than 8.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
```

In [29]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 4.99],
              [14.99, 2.39, 7.29]])
A[A>8]

array([ 9.99,  9.99, 14.99])

### <a name='3'></a> Exercise 31
The following array $ A $ is given. Replace elements greater than 10 with a fixed value of 10.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```

In [31]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.where(A>10,10,A)

array([[ 4.99,  3.49,  9.99],
       [ 1.99,  9.99, 10.  ],
       [10.  ,  2.39,  7.29]])

### <a name='4'></a> Exercise 32
Present the following $ A $ two-dimensional array as a "flattened" one-dimensional array.
```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])
```

In [33]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.ravel(A)

array([ 4.99,  3.49,  9.99,  1.99,  9.99, 14.99, 14.99,  2.39,  7.29])

### <a name='5'></a> Exercise 33
Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 0.0.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__
```
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])
```

In [34]:
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
np.zeros_like(A)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### <a name='6'></a> Exercise 34

Build an array of the same shape and data type as the $ A $ array and fill it with a constant value of 9.99.

```
A = np.array([[4.99, 3.49, 9.99],
              [1.99, 9.99, 14.99],
              [14.99, 2.39, 7.29]])
```
__Expected result:__

```
array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])
```

In [35]:
np.full_like(A,9.99)

array([[9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99],
       [9.99, 9.99, 9.99]])

### <a name='7'></a> Exercise 35
Build a two-dimensional array (lower triangular matrix) below:
```
array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])
```

In [36]:
np.tri(5)

array([[1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.]])

### <a name='8'></a> Exercise 36
Create any $ (2, 3, 4) $ 3-dimensional array.

In [37]:
A = np.array([[[4, 5, 4, 2],
               [6, 3, 5, 1],
               [5, 2, 1, 2]],
              
              [[7, 2, 3, 1],
               [6, 2, 0, 9],
               [0, 1, 9, 1]]])

A.shape

(2, 3, 4)

### <a name='9'></a> Exercise 37
Generate a two-dimensional array _(200, 300)_ filled with random values from 0 to 255 (inclusive) with data type _np.uint8_ and assign to the variable _image_.

In [43]:
image=np.random.randint(0,256,(200,300),np.uint8)
image

array([[131,  63, 154, ..., 218,  51, 154],
       [ 76, 187, 187, ..., 188, 235,  73],
       [177, 195, 159, ..., 214, 254, 194],
       ...,
       [156,  79, 153, ..., 249, 162, 188],
       [161, 132, 189, ...,  23, 134, 146],
       [ 32, 133, 251, ..., 218, 165, 220]], dtype=uint8)

### <a name='1'></a> Exercise 38
The following array $ A $ with the shape (2, 3) is given.
```
A = np.array([[4, 2, 1],
              [6, 4, 2]])
```

In [45]:
A = np.array([[4, 2, 1],
              [6, 4, 2]])
A.shape

(2, 3)

* Expand the array $ A $ by one dimension (add a new dimension at the beginning). Expected shape of the output array: _(1, 2, 3)_.

In [47]:
B=np.expand_dims(A,0)
B.shape

(1, 2, 3)

* Expand the array $ A $ by one dimension (add a new dimension at the end). Expected shape of the output array: _(2, 3, 1)_.


In [48]:
C=np.expand_dims(A,2)
C.shape

(2, 3, 1)

### <a name='2'></a> Exercise 39
Generate a three-dimensional array named _image_ with shape _(200, 300, 3)_ filled with random values from 0 to 255 inclusive and data type _np.uint8_.

In [58]:
image=np.random.randint(0,256,(200,300,3),np.uint8)
image.shape

(200, 300, 3)

### <a name='3'></a> Exercise 40
The _image_ array from the previous task is of the shape _(200, 300, 3)_. Follow the instructions:
* Extend the _image_ array by one dimension (add a new dimension at the beginning). Expected shape of the output array: _(1, 200, 300, 3)_.

In [59]:
image1=np.expand_dims(image,axis=0)
image1.shape

(1, 200, 300, 3)

* Extend the _image_ array by one dimension (add a new dimension at the end). Expected shape of the output array: _(200, 300, 3, 1)_.

In [61]:
image2=np.expand_dims(image,axis=3)
image2.shape

(200, 300, 3, 1)

### <a name='4'></a> Exercise 41
Two randomly generated arrays _image1_ and _image2_ are given.

```
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
```

Expand each of these arrays by adding one dimension at the beginning and then combine the arrays into one called _images_. Expected shape of array: _(2, 200, 300, 3)_.

In [63]:
image1 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
image2 = np.random.randint(low=0, high=256, size=(200, 300, 3), dtype=np.uint8)
print(image1.shape)
print(image2.shape)
image12=np.expand_dims(image1,axis=0)
print(image12.shape)
image22=np.expand_dims(image2,axis=0)
print(image22.shape)
images=np.append(image12,image22,axis=0)
print(images.shape)

(200, 300, 3)
(200, 300, 3)
(1, 200, 300, 3)
(1, 200, 300, 3)
(2, 200, 300, 3)


### <a name='5'></a> Exercise 42
From the _images_ array from the previous exercise, extract the first ten rows and the first ten columns from the third channel (index 2) for the first picture.

In [64]:
images[0, :10, :10, 2]

array([[152, 101,  31, 173, 164, 108, 213, 104, 248, 106],
       [ 45, 216, 194,  53, 175,  81, 194, 138, 176,   5],
       [185,  75, 225, 226, 204, 181, 150,  89,  52, 130],
       [ 48, 124, 117, 124,  14, 185,  40,  75, 128,  40],
       [ 89, 102, 136, 166, 223, 214, 183,  41,   7, 178],
       [212, 150, 235,  68, 242,   8,  55,  66,  27, 116],
       [ 12, 175,  46, 162, 165, 222,   6, 116,  39, 177],
       [155,  45,  81,  74, 111, 190, 144,  26, 168, 246],
       [145, 141, 138, 157, 141, 245, 125, 142, 252,  43],
       [  0, 138,   6, 186, 192,   5,  14, 217, 143, 106]], dtype=uint8)

### <a name='8'></a> Exercise 43
The following array $ A $ with the shape _(1, 2, 3)_ is given.

```
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
```

Remove the unnecessary first dimension and get an array of _(2, 3)_.

In [65]:
A = np.array([[[1, 2, 3],
               [6, 3, 2]]])
np.squeeze(A).shape

(2, 3)

### <a name='9'></a> Exercise 44
The following array $ A $ with the shape _(4, 1)_ is given.
```
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
```
Remove the unnecessary dimension and get an array with the shape _(4,)_.

In [66]:
A = np.array([[0.4],
              [0.9],
              [0.5],
              [0.6]])
np.squeeze(A).shape

(4,)

### <a name='10'></a> Exercise 45
The first image was extract from the _images_ array as follows:

In [67]:
image1 = images[:1]
image1.shape

(1, 200, 300, 3)

Using the knowledge from previous exercises, remove the unnecessary first dimension of the _image1_ array.

In [68]:
np.squeeze(image1).shape

(200, 300, 3)

### <a name='1'></a> Exercise 46
Two arrays $ A $ and $ B $ are given below:

```
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
```
* Concatenate these arrays as follows:

```
array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])
```

In [72]:
A = np.array([[3, 4, 5],
              [8, 3, 1]])
B = np.array([[0, 5, 2],
              [4, 2, 1]])
np.concatenate((A,B),axis=0)

array([[3, 4, 5],
       [8, 3, 1],
       [0, 5, 2],
       [4, 2, 1]])

In [73]:
np.concatenate((A,B),axis=1)

array([[3, 4, 5, 0, 5, 2],
       [8, 3, 1, 4, 2, 1]])

### <a name='2'></a> Exercise 47
The first array is given containing the data (_data_) and the second array containing the target class (_target_) for the given row:

```
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
Concatenate these arrays into one as shown below:

```
array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])
```

In [74]:
data = np.array([[4.3, 4.2],
                 [3.1, 3.6]])
target = np.array([[0],
                   [1]])
np.concatenate((data,target),axis=1)

array([[4.3, 4.2, 0. ],
       [3.1, 3.6, 1. ]])

### <a name='3'></a> Exercise 48
The following three one-dimensional arrays are given:
```
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
```
Transform each of these arrays into a column and concatenate them into one large array.

__Expected result:__
```
array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])
```

In [75]:
feature1 = np.array([1.6, 0.9, 2.2])
feature2 = np.array([0.4, 1.3, 3.2])
feature3 = np.array([1.4, 0.3, 1.2])
np.column_stack((feature1,feature2,feature3))

array([[1.6, 0.4, 1.4],
       [0.9, 1.3, 0.3],
       [2.2, 3.2, 1.2]])

### <a name='4'></a> Exercise 49
The following two-dimensional array is given:
```
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A
```
```
array([[0, 0, 4, 6, 2, 4, 1, 1],
       [0, 0, 6, 2, 2, 4, 1, 1],
       [0, 0, 1, 3, 5, 5, 1, 1],
       [0, 0, 3, 1, 5, 4, 1, 1],
       [0, 0, 2, 6, 1, 3, 1, 1]])
```
Split an array into three parts so that the first two columns formed the first array $ A1 $, four consecutive second array $ A2 $ and the last two third array $ A3 $.


In [76]:
A = np.random.randint(low=0, high=7, size=(5, 8))
A[:, :2] = 0
A[:, -2:] = 1
A

array([[0, 0, 5, 6, 3, 6, 1, 1],
       [0, 0, 0, 3, 4, 5, 1, 1],
       [0, 0, 6, 6, 4, 3, 1, 1],
       [0, 0, 2, 3, 3, 5, 1, 1],
       [0, 0, 3, 3, 5, 3, 1, 1]])

In [78]:
A1, A2, A3 = np.split(A, [2, 6], axis=1)
print(A1)
print(A2)
print(A3)

[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]
[[5 6 3 6]
 [0 3 4 5]
 [6 6 4 3]
 [2 3 3 5]
 [3 3 5 3]]
[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


### <a name='5'></a> Exercise 50
The following numpy array $ A $ is given:

```
A = np.random.randint(low=0, high=2, size=(10, 6))
```

Calculate the total number of non-zero elements for this array.

In [80]:
A = np.random.randint(low=0, high=2, size=(10, 6))
np.count_nonzero(A)

31

In [81]:
np.count_nonzero(A,axis=1)

array([4, 2, 4, 3, 4, 2, 3, 4, 2, 3], dtype=int64)

### <a name='6'></a> Exercise 51
An example numpy array $ A $ is given below:

```
A = np.random.randn(10, 4)
```

```
array([[-0.53441645, -1.49505387, -0.78925833,  0.74371128],
       [-0.21216142, -0.42686879,  0.50144833,  1.15818665],
       [ 0.25711687,  0.3145129 ,  1.37186213,  0.17555329],
       [-0.30928855,  0.6731255 , -0.25663018, -0.36782572],
       [ 1.27373362, -0.29195267, -2.65517605,  0.34551794],
       [-0.39551645, -0.28913686,  0.45293633, -0.16606091],
       [ 0.21493883, -2.02231493, -0.94305681,  1.40395874],
       [-0.0185508 , -1.67350462, -1.07253183, -0.99258618],
       [ 0.10234768, -0.43260928, -0.6591823 ,  0.0039373 ],
       [ 0.4777541 , -0.25902864, -0.57470921, -0.42149822]])
```

Set the numpy library option to print arrays with specified precision. Set its value to 4 and print the $ A $ array.

In [82]:
A = np.random.randn(10, 4)
np.set_printoptions(precision=4)
A

array([[-0.2301,  0.4029,  0.5841, -0.804 ],
       [-1.0264, -1.5541,  2.624 ,  0.08  ],
       [ 0.6515,  0.6126,  0.538 ,  1.8724],
       [-0.6142,  1.1204, -1.7809,  0.2785],
       [ 2.0133,  1.1917,  0.1402,  0.0249],
       [ 1.5383,  0.4387, -2.4889,  0.5131],
       [ 0.9335,  1.7674,  0.6054, -0.7559],
       [ 0.0347,  1.0015,  0.4811, -0.0724],
       [ 1.3235,  0.4918,  1.3539, -1.369 ],
       [ 0.351 , -1.4177,  0.1446,  0.7269]])

### <a name='7'></a> Exercise 52

The following numpy array $ A $ is given:

```
A = np.array([1.2e-6, 1.7e-7])
```
Set the precision value to 8. Then set the appropriate numpy library option to suppress mathematical notation. Print the array $ A $.

__Expected result:__
```
array([0.0000012 , 0.00000017])
```

In [84]:
A = np.array([1.2e-6, 1.7e-7])
np.set_printoptions(suppress=True,precision=8)
A

array([0.0000012 , 0.00000017])

### <a name='8'></a> Exercise 53
The following numpy array $ A $ is given:
```
A = np.random.randn(8, 4)
```
Remove the third column from the $ A $ array.

__Expected result:__
```
array([[-0.55692881, -0.66003196,  0.70856031],
       [ 0.22378737, -0.19796576, -0.16889332],
       [ 0.26062786,  0.29865445, -0.92259267],
       [-2.40317659,  1.79961876, -1.96495796],
       [ 0.13051561, -1.7085185 ,  0.54885043],
       [ 1.77268727,  0.38751181, -0.05141955],
       [-1.80858596, -0.45075211,  0.15332866],
       [ 1.94218961, -1.93679529, -1.83350954]])
```

In [87]:
A = np.random.randn(8, 4)
np.delete(A,[2],axis=1)

array([[ 1.45636022, -1.65405945,  0.75183057],
       [-1.21180056, -0.1887296 , -0.36221073],
       [-0.15863811,  0.84751818, -2.29397219],
       [-0.06109798, -0.35794349, -0.94000394],
       [-0.1849178 , -1.25225864,  3.16304873],
       [-0.16307179,  1.00530308,  1.26800398],
       [-0.68229775, -0.23087926, -1.39726021],
       [-0.70780828,  0.41718065, -0.07902472]])

### <a name='9'></a> Exercise 54

A one-dimensional array $ v $ (vector) is given:

```
v = np.array([3, 4, -2])
```
Calculate the norm of the vetor $ v $.


In [88]:
v = np.array([3, 4, -2])
np.linalg.norm(v)

5.385164807134504

### <a name='10'></a> Exercise 55
An example $ A $ array is given below:

```
A = np.random.randint(10, size=(100, 30))
```
Set the numpy library option to print 10 edge elements. Print the array $ A $.


In [90]:
A = np.random.randint(10, size=(100, 30))
np.set_printoptions(edgeitems=10)
A

array([[5, 3, 9, 1, 8, 4, 0, 9, 5, 3, ..., 2, 2, 0, 0, 2, 3, 5, 7, 8, 0],
       [1, 9, 6, 9, 8, 9, 5, 8, 6, 6, ..., 5, 3, 4, 7, 5, 8, 6, 3, 3, 8],
       [3, 6, 9, 8, 1, 6, 9, 7, 5, 9, ..., 4, 2, 0, 7, 3, 5, 3, 3, 9, 1],
       [0, 1, 9, 2, 1, 0, 4, 5, 6, 1, ..., 7, 2, 2, 5, 1, 8, 2, 0, 2, 5],
       [5, 9, 2, 3, 8, 7, 2, 7, 1, 5, ..., 4, 1, 0, 4, 1, 6, 5, 8, 5, 1],
       [0, 0, 6, 3, 6, 5, 5, 1, 0, 9, ..., 6, 7, 4, 0, 5, 6, 2, 3, 9, 7],
       [8, 3, 0, 0, 7, 8, 6, 2, 4, 6, ..., 8, 6, 2, 4, 4, 3, 5, 0, 2, 2],
       [2, 9, 8, 3, 2, 3, 2, 2, 8, 3, ..., 6, 0, 4, 0, 6, 8, 9, 1, 9, 8],
       [8, 9, 0, 0, 0, 0, 0, 4, 3, 6, ..., 5, 0, 6, 6, 4, 4, 4, 2, 4, 3],
       [1, 3, 5, 5, 8, 5, 3, 0, 9, 7, ..., 4, 2, 2, 3, 4, 6, 7, 6, 8, 8],
       ...,
       [6, 3, 9, 2, 9, 4, 9, 0, 7, 3, ..., 4, 1, 2, 8, 9, 2, 1, 7, 2, 7],
       [4, 7, 5, 1, 5, 9, 2, 4, 2, 2, ..., 4, 3, 8, 0, 8, 6, 4, 1, 0, 3],
       [4, 4, 3, 3, 1, 8, 1, 8, 4, 8, ..., 0, 2, 1, 9, 9, 5, 5, 8, 6, 6],
       [9, 9, 7, 6, 1, 8, 

### <a name='1'></a> Exercise 56
The following two arrays $ A $ and $ B $ are given:

```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```

Determine an array consisting of arithmetic means $ A $ and $ B $ of the corresponding elements.

__Expected result:__
```
array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])
```

In [94]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
c=np.mean((A,B),axis=0)
c

array([[3.5, 3.5, 5.5, 3.5],
       [5.5, 3. , 1.5, 5.5]])

### <a name='2'></a> Exercise 57
The following two arrays $ A $ and $ B $ are given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
```
Multiply arrays element-by-element (element-wise).

In [95]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
B = np.array([[4, 3, 2, 5],
              [6, 3, 1, 6]])
A*B

array([[12, 12, 18, 10],
       [30,  9,  2, 30]])

### <a name='3'></a> Exercise 58
The following numpy array $ A $ is given:
```
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
```
Determine the root of each element of the array $ A $.

In [96]:
A = np.array([[3, 4, 9, 2],
              [5, 3, 2, 5]])
np.sqrt(A)

array([[1.7321, 2.    , 3.    , 1.4142],
       [2.2361, 1.7321, 1.4142, 2.2361]])

### <a name='5'></a> Exercise 59
Two two-dimensional arrays are provided, numpy $ A $ and $ B $.  
$ A $ - dimension matrix $ (3, 2) $  
$ B $ - dimension matrix $ (2, 3) $  
```
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
```
Perform matrix multiplication of $ A $ and $ B $ arrays.

In [98]:
A = np.array([[2, 3],
              [-4, 2],
              [5, 0]])
B = np.array([[4, 3, 2],
              [-1, 0, 2]])
np.dot(A,B)

array([[  5,   6,  10],
       [-18, -12,  -4],
       [ 20,  15,  10]])

### <a name='6'></a> Exercise 60
The following array (square matrix) $ A $ is given:

```
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
```
Compute the determinant of the $ A $ matrix.

In [99]:
A = np.array([[-2, 0, 4],
              [5, 2, -1],
              [-4, 2, 4]])
np.linalg.det(A)

51.999999999999986

### <a name='7'></a> Exercise 61
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Calculate eigenvalues and their corresponding eigenvectors of the $ A $ matrix.

In [101]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
print(np.linalg.eig(A))
print(np.linalg.eigvals(A))

(array([-9.2462, -3.    ,  7.2462]), array([[-0.6262, -0.8944,  0.8902],
       [-0.3131,  0.    ,  0.4451],
       [ 0.7141,  0.4472, -0.0976]]))
[-9.2462 -3.      7.2462]


### <a name='8'></a> Exercise 62
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the inverse matrix to the $ A $ matrix.

In [102]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
np.linalg.inv(A)

array([[-0.2139,  0.7562,  0.2388],
       [ 0.0597,  0.0448,  0.1194],
       [ 0.0995, -0.2587, -0.1343]])

### <a name='9'></a> Exercise 63
The following array (square matrix) $ A $ is given:
```
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
```
Find the trace of the square matrix $ A $ (sum of elements on the main diagonal).

In [104]:
A = np.array([[5, 8, 16],
              [4, 1, 8],
              [-4, 4, -11]])
np.trace(A)

-5

### Exercise 63 continued
Transpose the $ A $ matrix.

In [105]:
np.transpose(A)

array([[  5,   4,  -4],
       [  8,   1,   4],
       [ 16,   8, -11]])

### <a name='1'></a> Exercise 64
The following $ A $ array is given:
```
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
```
From the second row of the $ A $ array, randomly shuffle the rows in the array.

In [123]:
A = np.array([['id', 'price'],
              ['001', 14.99],
              ['002', 4.99],
              ['003', 7.99],
              ['004', 2.49],
              ['005', 1.49]])
np.random.shuffle(A[1:])
A

array([['id', 'price'],
       ['004', '2.49'],
       ['002', '4.99'],
       ['003', '7.99'],
       ['001', '14.99'],
       ['005', '1.49']], dtype='<U5')

### <a name='2'></a> Exercise 65
The following array $ A $ is given:

```
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
```
Return an array of indexes that will sort the array $ A $ in ascending order.

__Expected result:__

```
array([5, 2, 1, 0, 4, 3])
```

In [124]:
A = np.array([0.2, 0.15, 0.1, 0.3, 0.2, 0.05])
np.argsort(A)

array([5, 2, 1, 0, 4, 3], dtype=int64)

### <a name='3'></a> Exercise 66

The following array $ A $ is given:
```
A = np.random.randn(10, 8)
```
Round the values of this array to three decimal places.

In [126]:
A = np.random.randn(10, 8)
np.round(A,3)

array([[ 0.257,  0.315,  1.372,  0.176, -0.309,  0.673, -0.257, -0.368],
       [ 1.274, -0.292, -2.655,  0.346, -0.396, -0.289,  0.453, -0.166],
       [ 0.215, -2.022, -0.943,  1.404, -0.019, -1.674, -1.073, -0.993],
       [ 0.102, -0.433, -0.659,  0.004,  0.478, -0.259, -0.575, -0.421],
       [ 0.34 , -0.007,  0.767, -1.15 , -0.775,  0.773, -0.802,  1.384],
       [ 1.405,  1.392, -0.881,  0.077, -0.493,  0.923,  1.707,  0.874],
       [ 0.009, -0.366,  0.649, -1.223,  0.536, -0.915,  0.621, -0.161],
       [-0.388, -0.886, -0.357,  0.556,  1.044,  0.526,  1.364,  2.539],
       [-0.324, -0.206, -1.44 ,  1.191,  1.299, -0.867,  0.618,  1.217],
       [ 0.226,  0.847,  0.175, -1.217,  1.049,  1.325,  0.735, -0.954]])

### <a name='4'></a> Exercise 67
Determine the roots of the polynomial:
* $W(x) = 4x^2 + 5x + 1$

In [127]:
A=np.array([4,5,1])
np.roots(A)

array([-1.  , -0.25])

### <a name='5'></a> Exercise 68
Determine the roots of polynomials:
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
* $R(x) = 2x^3 -5x + 1$

In [129]:
Q=np.array([2,4,-5,1])
R=np.array([2,-5,1])
print('Roots of Q :',np.roots(Q))
print('Roots of R :',np.roots(R))

Roots of Q : [-2.9161  0.6539  0.2622]
Roots of R : [2.2808 0.2192]


### <a name='6'></a> Exercise 69
Polynomials are given:
* $W(x) = 4x^2 + 5x + 1$
* $Q(x) = 2x^3 + 4x^2 -5x + 1$
*Perform*:
* $ W (x) + Q (x) $

In [130]:
W=np.array([4,5,1])
Q=np.array([2,4,-5,1])
np.polyadd(W,Q)

array([2, 8, 0, 2])

$W(x) - Q(x)$

In [131]:
np.polysub(W,Q)

array([-2,  0, 10,  0])

$W(x) * Q(x)$

In [132]:
np.polymul(W,Q)

array([  8,  26,   2, -17,   0,   1])

$W(x) + 2Q(x)$

In [133]:
np.polyadd(W,2*Q)

array([ 4, 12, -5,  3])

### <a name='7'></a> Exercise 70
The array below is given:

```
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
```
Use the sign function for the array $ A $. As a reminder, the function works as follows: returns -1 for negative values, zero for zero, and 1 for positive values.

__Expected result:__

```
array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])
```

In [134]:
A = np.array([[-4, 3, 0, 1, -5],
              [6, -4, -2, 1, 3]])
np.sign(A)

array([[-1,  1,  0,  1, -1],
       [ 1, -1, -1,  1,  1]])

### <a name='8'></a> Exercise 71
Using the _np.arange()_ function, generate the following array:

```
array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')
```

In [135]:
np.arange('2021-01-01', '2021-02-01', dtype='datetime64[D]')

array(['2021-01-01', '2021-01-02', '2021-01-03', '2021-01-04',
       '2021-01-05', '2021-01-06', '2021-01-07', '2021-01-08',
       '2021-01-09', '2021-01-10', '2021-01-11', '2021-01-12',
       '2021-01-13', '2021-01-14', '2021-01-15', '2021-01-16',
       '2021-01-17', '2021-01-18', '2021-01-19', '2021-01-20',
       '2021-01-21', '2021-01-22', '2021-01-23', '2021-01-24',
       '2021-01-25', '2021-01-26', '2021-01-27', '2021-01-28',
       '2021-01-29', '2021-01-30', '2021-01-31'], dtype='datetime64[D]')

### <a name='10'></a> Exercise 72
Using the _np.datetime64()_ function, generate today's date.

In [136]:
np.datetime64('today')

numpy.datetime64('2022-08-18')

### <a name='2'></a> Exercise 73 
Two $ A $ and $ B $ arrays are given:
```
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
```
Merge them together as shown below:

```
array(['001XC', '002YC', '003ZC'], dtype='<U5')
```

In [137]:
A = np.array(['001', '002', '003'], dtype=np.str)
B = np.array(['XC', 'YC', 'ZC'], dtype=np.str)
np.char.add(A,B)

array(['001XC', '002YC', '003ZC'], dtype='<U5')

### <a name='3'></a> Exercise 74
The array below is given:

```
A = np.array(['1', '2', '3'], dtype=np.str)
```
Add '000' (3 zeros) to the beginning of each element of the array.

In [138]:
A = np.array(['1', '2', '3'], dtype=np.str)
np.char.add('000',A)

array(['0001', '0002', '0003'], dtype='<U4')

### <a name='4'></a> Exercise 75
The array below is given:
```
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
```
Split each element of the above array by spaces, obtaining a list of values in each place.

__Expected result:__
```
array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)
```

In [140]:
A = np.array([['PLW CDR 11B TEN', 'AMC LPP'],
              ['CDR PKO KGH', 'CCC QMK']], dtype=np.str)
np.char.split(A)

array([[list(['PLW', 'CDR', '11B', 'TEN']), list(['AMC', 'LPP'])],
       [list(['CDR', 'PKO', 'KGH']), list(['CCC', 'QMK'])]], dtype=object)

### <a name='5'></a> Exercise 76
The array below is given:
```
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
```
Replace all # with spaces and then remove any unnecessary spaces around the text.

__Expected result:__
```
array([['summer time mood'],
       ['sport time']], dtype='<U17')
```

In [146]:
A = np.array([['#summer#time#mood'],
              ['#sport#time']])
np.char.split(np.char.replace(A,'#',' '))

array([[list(['summer', 'time', 'mood'])],
       [list(['sport', 'time'])]], dtype=object)

### <a name='6'></a> Exercise 77
The following array is provided:

```
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
```
Count the number of occurrences of the word 'time' in each element of the $ A $ array.

In [149]:
A = np.array([['#summer#time#mood', '#vibe'],
              ['#sport#time', '#good#time'],
              ['#event#summer', '#fast#move']])
np.char.count(A,'time')

array([[1, 0],
       [1, 1],
       [0, 0]])

### <a name='7'></a> Exercise 78
The following text is provided containing data (companies from the WIG20 index):

```
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""
```

__Columns mean \:__

Instrument | ISIN code | Package | Package (PLN) | Share in portfolio (%) | Share in trading shares and PDAs per session (%) | Average spread per session

Split text into lines. Then divide each line by the tab character `\t` and build a numpy array (without headers) containing the following data. Assign the resulting array to the _result_ variable.

__Expected result:__
```
array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891', '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831', '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000', '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900', '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733', '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461', '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354', '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607', '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787', '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820', '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647 357 000', '4 285 503 340', '2,756', '1,16', '13'],
       ['PEKAO', 'PLPEKAO00016', '176 379 000', '9 619 710 660', '6,185', '5,27', '9'],
       ['PGE', 'PLPGER000010', '796 776 000', '3 561 588 720', '2,290', '2,88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1 624 608 000', '6 072 784 704', '3,905', '1,56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289 049 000', '17 701 360 760', '11,382', '12,44', '8'],
       ['PKOBP', 'PLPKO0000016', '857 593 000', '18 807 014 490', '12,093', '10,49', '9'],
       ['PLAY', 'LU1642887738', '114 151 000', '3 696 209 380', '2,377', '1,47', '16'],
       ['PZU', 'PLPZU0000011', '568 305 000', '17 515 160 100', '11,262', '6,64', '6'],
       ['SANPL', 'PLBZ00000044', '33 207 000', '5 213 499 000', '3,352', '1,91', '18'],
       ['TAURONPE', 'PLTAURN00011', '1 043 590 000', '1 252 308 000', '0,805', '1,21', '33']],
      dtype='<U14')
```

In [150]:
text = """ALIOR	PLALIOR00045	88 860 000	1 386 216 000	0,891	2,16	14
CCC	PLCCC0000016	27 918 000	1 292 603 400	0,831	5,28	42
CDPROJEKT	PLOPTTC00011	67 348 000	22 864 646 000	14,702	7,39	7
CYFRPLSAT	PLCFRPT00013	275 301 000	6 854 994 900	4,408	1,17	14
DINOPL	PLDINPL00011	47 937 000	8 916 282 000	5,733	9,13	12
JSW	PLJSW0000015	52 636 000	716 902 320	0,461	1,51	24
KGHM	PLKGHM000017	136 410 000	9 881 540 400	6,354	4,78	8
LOTOS	PLLOTOS00025	86 543 000	5 609 717 260	3,607	2,91	16
LPP	PLLPP0000011	1 306 000	7 444 200 000	4,787	1,43	19
MBANK	PLBRE0000012	12 997 000	2 830 746 600	1,820	0,42	24
ORANGEPL	PLTLKPL00017	647 357 000	4 285 503 340	2,756	1,16	13
PEKAO	PLPEKAO00016	176 379 000	9 619 710 660	6,185	5,27	9
PGE	PLPGER000010	796 776 000	3 561 588 720	2,290	2,88	18
PGNIG	PLPGNIG00014	1 624 608 000	6 072 784 704	3,905	1,56	12
PKNORLEN	PLPKN0000018	289 049 000	17 701 360 760	11,382	12,44	8
PKOBP	PLPKO0000016	857 593 000	18 807 014 490	12,093	10,49	9
PLAY	LU1642887738	114 151 000	3 696 209 380	2,377	1,47	16
PZU	PLPZU0000011	568 305 000	17 515 160 100	11,262	6,64	6
SANPL	PLBZ00000044	33 207 000	5 213 499 000	3,352	1,91	18
TAURONPE	PLTAURN00011	1 043 590 000	1 252 308 000	0,805	1,21	33"""

lines = text.splitlines()
lines = [line.split('\t') for line in lines]
result = np.array(lines, dtype=np.str)
result

array([['ALIOR', 'PLALIOR00045', '88 860 000', '1 386 216 000', '0,891',
        '2,16', '14'],
       ['CCC', 'PLCCC0000016', '27 918 000', '1 292 603 400', '0,831',
        '5,28', '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67 348 000', '22 864 646 000',
        '14,702', '7,39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275 301 000', '6 854 994 900',
        '4,408', '1,17', '14'],
       ['DINOPL', 'PLDINPL00011', '47 937 000', '8 916 282 000', '5,733',
        '9,13', '12'],
       ['JSW', 'PLJSW0000015', '52 636 000', '716 902 320', '0,461',
        '1,51', '24'],
       ['KGHM', 'PLKGHM000017', '136 410 000', '9 881 540 400', '6,354',
        '4,78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86 543 000', '5 609 717 260', '3,607',
        '2,91', '16'],
       ['LPP', 'PLLPP0000011', '1 306 000', '7 444 200 000', '4,787',
        '1,43', '19'],
       ['MBANK', 'PLBRE0000012', '12 997 000', '2 830 746 600', '1,820',
        '0,42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '64

### <a name='8'></a> Exercise 79
From the _result_ array from the previous exercise, remove all spaces in the text and replace all commas with periods.

In [151]:
result = np.char.replace(result, ' ', '')
result = np.char.replace(result, ',', '.')
result

array([['ALIOR', 'PLALIOR00045', '88860000', '1386216000', '0.891',
        '2.16', '14'],
       ['CCC', 'PLCCC0000016', '27918000', '1292603400', '0.831', '5.28',
        '42'],
       ['CDPROJEKT', 'PLOPTTC00011', '67348000', '22864646000', '14.702',
        '7.39', '7'],
       ['CYFRPLSAT', 'PLCFRPT00013', '275301000', '6854994900', '4.408',
        '1.17', '14'],
       ['DINOPL', 'PLDINPL00011', '47937000', '8916282000', '5.733',
        '9.13', '12'],
       ['JSW', 'PLJSW0000015', '52636000', '716902320', '0.461', '1.51',
        '24'],
       ['KGHM', 'PLKGHM000017', '136410000', '9881540400', '6.354',
        '4.78', '8'],
       ['LOTOS', 'PLLOTOS00025', '86543000', '5609717260', '3.607',
        '2.91', '16'],
       ['LPP', 'PLLPP0000011', '1306000', '7444200000', '4.787', '1.43',
        '19'],
       ['MBANK', 'PLBRE0000012', '12997000', '2830746600', '1.820',
        '0.42', '24'],
       ['ORANGEPL', 'PLTLKPL00017', '647357000', '4285503340', '2.756',
        '1.16', 

Then extract column 'Share in portfolio (%)' convert its type to _float_ and calculate the sum for this column. Check if it's 100%.

In [152]:
result[:, 4].astype(float).sum()

100.001

### <a name='9'></a> Exercise 80
From the _result_ array, extract all the rows with the company name beginning with the letter P and assign it to the variable _stocks_startswith_P_.

__Expected result:__

```
array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185', '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290', '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905', '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382', '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093', '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377', '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262', '6.64', '6']], dtype='<U12')
```

In [155]:
stocks_startswith_P = result[np.char.startswith(result[:, 0], 'P')]
stocks_startswith_P

array([['PEKAO', 'PLPEKAO00016', '176379000', '9619710660', '6.185',
        '5.27', '9'],
       ['PGE', 'PLPGER000010', '796776000', '3561588720', '2.290',
        '2.88', '18'],
       ['PGNIG', 'PLPGNIG00014', '1624608000', '6072784704', '3.905',
        '1.56', '12'],
       ['PKNORLEN', 'PLPKN0000018', '289049000', '17701360760', '11.382',
        '12.44', '8'],
       ['PKOBP', 'PLPKO0000016', '857593000', '18807014490', '12.093',
        '10.49', '9'],
       ['PLAY', 'LU1642887738', '114151000', '3696209380', '2.377',
        '1.47', '16'],
       ['PZU', 'PLPZU0000011', '568305000', '17515160100', '11.262',
        '6.64', '6']], dtype='<U12')

### <a name='10'></a> Exercise 81
Using the variable _stocks_startswith_P_, calculate the total share of companies whose name begins with the letter P. Round the result to two decimal places.

In [156]:
np.round(stocks_startswith_P[:, 4].astype(float).sum(), 2)

49.49

In [157]:
np.set_printoptions(linewidth=160, suppress=True)

### <a name='1'></a> Exercise 82
The following string _wig_games_raw_ is provided containing data on the WIG.GAMES sector index:

```
wig_games_raw = """Profile	Time	Course	Change	Change%	Ref.	Open	Low	High	Volume	Turn	Share
11B (11BIT)	17 kwi 17:01	391.00	+8.00	(+2.09%)	383.00	383.50	383.00	394.00	12 784	4 994 874	19.034%
CDR (CDPROJEKT)	17 kwi 17:01	339.50	+5.30	(+1.59%)	334.20	338.30	337.00	344.20	233 059	79 245 368	39.618%
CIG (CIGAMES)	17 kwi 17:03	0.742	-0.012	(-1.59%)	0.754	0.772	0.730	0.772	1 311 078	971 459	1.855%
PLW (PLAYWAY)	17 kwi 17:03	387.50	+18.00	(+4.87%)	369.50	374.00	373.00	388.00	33 206	12 661 786	10.638%
TEN (TSGAMES)	17 kwi 17:02	349.50	+22.50	(+6.88%)	327.00	332.00	330.00	353.50	39 793	13 697 060	28.855%"""
```
Build a numpy array from this data and name it _wig_games_.

__Expected result:__
```
array([['Profile', 'Time', 'Course', 'Change', 'Change%', 'Ref.', 'Open', 'Low', 'High', 'Volume', 'Turn', 'Share'],
       ['11B(11BIT)', '17kwi17:01', '391.00', '+8.00', '(+2.09%)', '383.00', '383.50', '383.00', '394.00', '12784', '4994874', '19.034%'],
       ['CDR(CDPROJEKT)', '17kwi17:01', '339.50', '+5.30', '(+1.59%)', '334.20', '338.30', '337.00', '344.20', '233059', '79245368', '39.618%'],
       ['CIG(CIGAMES)', '17kwi17:03', '0.742', '-0.012', '(-1.59%)', '0.754', '0.772', '0.730', '0.772', '1311078', '971459', '1.855%'],
       ['PLW(PLAYWAY)', '17kwi17:03', '387.50', '+18.00', '(+4.87%)', '369.50', '374.00', '373.00', '388.00', '33206', '12661786', '10.638%'],
       ['TEN(TSGAMES)', '17kwi17:02', '349.50', '+22.50', '(+6.88%)', '327.00', '332.00', '330.00', '353.50', '39793', '13697060', '28.855%']], dtype='<U14')
```


In [159]:
wig_games_raw = """Profile    Time    Course    Change    Change%    Ref.    Open    Low    High    Volume    Turn    Share
11B (11BIT)    17 kwi 17:01    391.00    +8.00    (+2.09%)    383.00    383.50    383.00    394.00    12 784    4 994 874    19.034%
CDR (CDPROJEKT)    17 kwi 17:01    339.50    +5.30    (+1.59%)    334.20    338.30    337.00    344.20    233 059    79 245 368    39.618%
CIG (CIGAMES)    17 kwi 17:03    0.742    -0.012    (-1.59%)    0.754    0.772    0.730    0.772    1 311 078    971 459    1.855%
PLW (PLAYWAY)    17 kwi 17:03    387.50    +18.00    (+4.87%)    369.50    374.00    373.00    388.00    33 206    12 661 786    10.638%
TEN (TSGAMES)    17 kwi 17:02    349.50    +22.50    (+6.88%)    327.00    332.00    330.00    353.50    39 793    13 697 060    28.855%"""

In [160]:
lines = wig_games_raw.splitlines()
lines = [line.split('\t') for line in lines]
wig_games = np.array(lines, dtype=np.str)
wig_games = np.char.replace(wig_games, ' ', '')
wig_games

array([['ProfileTimeCourseChangeChange%Ref.OpenLowHighVolumeTurnShare'],
       ['11B(11BIT)17kwi17:01391.00+8.00(+2.09%)383.00383.50383.00394.0012784499487419.034%'],
       ['CDR(CDPROJEKT)17kwi17:01339.50+5.30(+1.59%)334.20338.30337.00344.202330597924536839.618%'],
       ['CIG(CIGAMES)17kwi17:030.742-0.012(-1.59%)0.7540.7720.7300.77213110789714591.855%'],
       ['PLW(PLAYWAY)17kwi17:03387.50+18.00(+4.87%)369.50374.00373.00388.00332061266178610.638%'],
       ['TEN(TSGAMES)17kwi17:02349.50+22.50(+6.88%)327.00332.00330.00353.50397931369706028.855%']], dtype='<U88')